name = "hp-delivery-worker"
account_id = "04e84f55bcdf503c245a133eea53f64a"
workers_dev = true
compatibility_date = "2026-04-07"
main = "src/index.js"

[[kv_namespaces]]
binding = "RATE_LIMIT"
id = "16c5916428b641eeb0c8e24b3e2e02ac"

[vars]
SA_CLIENT_EMAIL = "kapturit-worker@kapturit-portal.iam.gserviceaccount.com"
# SA_PRIVATE_KEY → configurar como secret en Cloudflare Dashboard → Workers → hp-delivery-worker → Settings → Variables